### PR TITLE
Fix Derivative issue discussed in #971

### PR DESCRIPTION
**Pull request by mmatera**
This PR prevents ``True'``, ``False'`` and ``List'`` be evaluated producing the error reported in #971. Comments explaining how the rule for evaluating `Derivative` over anonymous functions works was added.

### CODE REVIEW

**Comment by mmatera** [comment]
Remember that in an eval method, return None means that the expression is left without changes and the evaluation stops. Another possibility would be to add another condition in the LHS of the WL rule, to make that the expression does not match if applied to a Locked symbol.

**Comment by rocky** [comment]
> Remember that in an eval method, return None means that the expression is left without changes and the evaluation stops. Another possibility would be to add another condition in the LHS of the WL rule, to make that the expression does not match if applied to a Locked symbol.

This seems even hackier. So let's go with what you propose. And again, thanks for documenting some of the mess we inherited.

Is the handling of  for `List'` correct though with this change? (I realize it is better behavior, but is it _correct_?)

**Comment by rocky** [comment]
Add some small tests to `test/builtin/numbers/test_calculus.py`

**Comment by mmatera** [comment]
> Is the handling of  for `List'` correct though with this change? (I realize it is better behavior, but is it _correct_?) 

This is the behavior in WMA.

**Comment by rocky** [comment]
> > Is the handling of  for `List'` correct though with this change? (I realize it is better behavior, but is it _correct_?)
> 
> This is the behavior in WMA.

Ok. Why is `{1} &` printed?

**Comment by mmatera** [comment]
> > > Is the handling of  for `List'` correct though with this change? (I realize it is better behavior, but is it _correct_?)
> > 
> > 
> > This is the behavior in WMA.
> 
> Ok. Why is `{1} &` printed?

Funny... Tomorrow I will check again.

**Comment by mmatera** [comment]
> > > Is the handling of  for `List'` correct though with this change? (I realize it is better behavior, but is it _correct_?)
> > 
> > 
> > This is the behavior in WMA.
> 
> Ok. Why is `{1} &` printed?

@rocky: indeed, you are right. This makes sense because   `Differential[1][List][x]`  ->     `D[List[x],x]->{1}`
But this is the result of  applying  `{1}&` to `x`. I am going to modify the code to produce this.

**Comment by mmatera** [comment]
I checked again by hand all the special cases that could produce the recursion error:

```
s = Select[s, MemberQ[Attributes[Evaluate[#1]], Locked] &];
Table[q -> (Derivative[1][Evaluate[ToExpression[q]]] // FullForm), {q,
    s}] // TableForm
```

**Pull request merged**
