### PR TITLE
Place options 'All' and 'None' in correct section

### PR DESCRIPTION
**Pull request by rocky**
And go over docs and summary text for these. Add examples.

### CODE REVIEW

**Review by mmatera — APPROVED** [review]
LGTM

**Comment by rocky** [comment]
@mmatera I am not seeing some of the remaining functions `LevelQ` and `NotListQ`  listed on the Wolfram site. Do they still work?  (Server I use to check this has been unavailable).

**Comment by mmatera** [comment]
> @mmatera I am not seeing some of the remaining functions `LevelQ` and `NotListQ` listed on the Wolfram site. Do they still work? (Server I use to check this has been unavailable).

nop, these symbols seem to be removed from WMA

**Comment by rocky** [comment]
If we know when they were removed I will create a Pymathics module for compatibility with XXX, and add that there.

**Comment by mmatera** [comment]
> If we know when they were removed I will create a Pymathics module for compatibility with XXX, and move this out of core and into this..

I never have used that symbol. Legacy versions of the WMA documentation are online. For example,

https://reference.wolfram.com/legacy/v4

has the documentation of version 4. However, I could not find a reference to these symbols.

**Comment by mmatera** [comment]
On the other hand, we use `LevelQ` for defining rules in the module `mathics.builtin.functional.apply_fns_to_lists`

**Comment by rocky** [comment]
This is weird. Something similar happens for 'NotListQ' - it is used only in signature testing. 

And it is used a _lot_ in SymJa rules in signatures as well which leads me to believe this _is_ a part of Mathematica, just one not documented. 

We have the option of keeping this but removing it from user-printed documentation. 

Your thoughts?

**Comment by rocky** [comment]
Or we could _admit_ that it exists for use in function signature applicability and ask people not to use. I don't know.

But personally, I don't like the idea of saying nothing and not informing what's up.

**Comment by mmatera** [comment]
I think we should keep it and document it, but maybe move the symbols to another section.

**Comment by mmatera** [comment]
A good place for these symbols would be `mathics.builtin.testing_expressions.list_oriented`. Also probably we should remove the (unexisting) link to Wolfram Reference.

**Pull request merged**
