### PR TITLE
Opacity

### PR DESCRIPTION
**Pull request by mmatera**
Here I included an implementation for handing the ``Opacity`` directive. What is remaining to do is to implement it in the asy formatter, as well as in the 3D threejs side, but I think that this is something that @TiagoCavalcante can handle better than me.

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/279"></a>

### CODE REVIEW

**Comment by TiagoCavalcante** [comment]
@mmatera it already is there, all [primitives](https://mathics3.github.io/mathics-threejs-backend/primitives/) support opacity.

**Comment by rocky** [comment]
> Here I included an implementation for handing the `Opacity` directive. What is remaining to do is to implement it in the asy formatter, 

For asymptote, ["filldraw" has an opacity](https://asymptote.sourceforge.io/doc/Pens.html) parameter that goes from 0 to 1. But boundaries of a 3D surface seem also need import the bsp package. See https://tex.stackexchange.com/questions/532225/opacity-in-asymptote

**Comment by rocky** [comment]
Just tried it. Looks good!

**Comment by mmatera** [comment]
* SVG seems to work OK.
* In Asymptote, opacity seems to work when I run it "online", but when the documentation is generated, the parameter is not taken into account.
* For some reason, threejs / mathics-threejs-backend / m is not working right, so I made the changes in Graphics3D blind. @rocky, did you confirm me that it is working?

**Comment by rocky** [comment]
> * SVG seems to work OK.
> * In Asymptote, opacity seems to work when I run it "online", but when the documentation is generated, the parameter is not taken into account.
> * For some reason, threejs / mathics-threejs-backend / m is not working right, so I made the changes in Graphics3D blind. @rocky, did you confirm me that it is working?

Graphics3D has been broken for a while. I never claimed this worked on Graphics3D. It has been broken for a while. Last mention of its brokenness was in https://github.com/Mathics3/mathics-django/issues/149

**Comment by mmatera** [comment]
> > * SVG seems to work OK.
> > * In Asymptote, opacity seems to work when I run it "online", but when the documentation is generated, the parameter is not taken into account.
> > * For some reason, threejs / mathics-threejs-backend / m is not working right, so I made the changes in Graphics3D blind. @rocky, did you confirm me that it is working?
> 
> Graphics3D has been broken for a while. I never claimed this worked on Graphics3D. It has been broken for a while. Last mention of its brokenness was in [Mathics3/mathics-django#149](https://github.com/Mathics3/mathics-django/issues/149)

OK, good to know then.

**Pull request merged**
