### PR TITLE
support for sympy 1.12

### PR DESCRIPTION
**Pull request by mmatera**
This PR allows to use sympy 1.12, without breaking the tests, fixing #881.

### CODE REVIEW

**Comment by rocky** [comment]
This is good. Make a new branch from tag 6.0.1 (I think the SHA1 is 62b8b7f1 and open an additional PR applying this commit to that branch. Thanks.

**Comment by mmatera** [comment]
For some reason, when I try to make a PR over these branches, github just shows me the differences, but no a PR button.

**Comment by rocky** [comment]
The branch current

> For some reason, when I try to make a PR over these branches, github just shows me the differences, but no a PR button.

That is because the branch currently has the first commit as part of it.

**Comment by rocky** [comment]
LGTM

**Pull request merged**
