### PR TITLE
Try Rubi as a git submodule

### PR DESCRIPTION
**Pull request by rocky**
Thoughts about doing this? 
@aravindh-krishnamoorthy  ?

### CODE REVIEW

**Comment by rocky** [comment]
> @rocky, I think this would be OK once mathics-ruby loads and works properly. By now, I would do the opposite: add a github-action test on mathics-ruby, and check against the branches of mathics-core that improve the required support.

Yes, that makes sense. But here we need https://github.com/Mathics3/mathics-core/pull/1176 to finish. This corrects some bugs in handling the "optional" operator in pattern matching.  When you get a chance please look that over since you know far more about Mathics3's pattern-matching code (and WMA) than I.  Right now, these changes are pretty small.

**Comment by aravindh-krishnamoorthy** [comment]
Indeed, this sounds good once basic Rubi starts working...

**Comment by rocky** [comment]
Now that Rubi has merged, this is your last chance to weigh in before we merge this.

Of course, in order to use Rubi, you'll have to use a branch to make TimeConstrained work.  @aravindh-krishnamoorthy started a discussion thread for that.

**Review by mmatera — APPROVED** [review]
Ok, let's try this. LGTM

**Pull request merged**
