### PR TITLE
Make explicit the need for serialization ...

### PR DESCRIPTION
**Pull request by rocky**
in Definition and Rule.

Some small linting was doine to shorten long lines, remove an uneeded import, correct a type annotation here and there.

test_serialization was expanded to include a rule test.

test_calculus was split and moved into test/builtin/calculus.

### CODE REVIEW

**Comment by rocky** [comment]
Googling for pickle replacements turns up [dill](https://pypi.org/project/dill/) and JSON which seems less general.

We should check that dill works.

**Review by mmatera — APPROVED** [review]
LGTM

**Comment by rocky** [comment]
Sorry for the delay  - this work you did is good and I think will allow us to separate module loading from definitions loading.

**Comment by mmatera** [comment]
@rocky, thanks for the review and the improvements.

**Comment by mmatera** [comment]
> Googling for pickle replacements turns up [dill](https://pypi.org/project/dill/) and JSON which seems less general.
> 
> We should check that dill works.

I remember that some years ago I tried dill, and for some reason pickle still was the best option. But I can look again.

**Comment by rocky** [comment]
> > Googling for pickle replacements turns up [dill](https://pypi.org/project/dill/) and JSON which seems less general.
> > We should check that dill works.
> 
> I remember that some years ago I tried dill, and for some reason pickle still was the best option. But I can look again.

It might have been because pickle can store Python objects that have pointers in them. But this might not be a good thing. 

As for the security issues see https://medium.com/ochrona/python-pickle-is-notoriously-insecure-d6651f1974c9 and https://nedbatchelder.com/blog/202006/pickles_nine_flaws.html

**Pull request merged**
