### PR TITLE
Fix set ops another round

### PR DESCRIPTION
**Pull request by mmatera**
With this PR, that comes after #601, #602, #603 and #604, allows to load the mymakeboxes.m package, and hopefully, should help to load other packages like KnotTheory, Feyncalc and others.

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/605"></a>

### CODE REVIEW

**Comment by rocky** [comment]
@mmatera - This is and #601 to #604 are interesting and I would like to go through these and understand in more detail. I haven't had the time to do so, but will very soon. Thanks for doing this. 

I am excited to hear that Mathics package loading may now be fixed. This is very important.

**Comment by rocky** [comment]
> With this PR, that comes after #601, #602, #603 and #604, 

Does this really depend on #604?  At any rate perhaps the merge branch should be #603 (or #604) instead of master. If either of these lands onto master, _then_  this can be merged to master directly. What we've seen is that when there are lot of changes to the dependent branches (and PRs here have to go in the order they were done), then we are likely to create merge conflicts here where none were needed.

**Comment by mmatera** [comment]
> .

#604 and this are independent. What I was saying it that I need these PR to make mymakeboxes.m work.

**Comment by mmatera** [comment]
reformulated in #616 as a PR over #603

**Pull request closed without merging**
