### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by mmatera**
Let's start by trying this

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/246"></a>

### CODE REVIEW

**Comment by rocky** [comment]
I'd like to see a section that helps us categorize priority.  Something needed for a popular opens-source project (e.g. Rubi, KnotTheory) or a in order to support distribution,( e.g. SUSE, condaforge, PyPI) would be at one end. At the other end would be have been fooling around learning Mathematica and came across a couple of missing functions. 

Another way to tackle this would be to ask for details as to why Mathics interests the person, e.g. personal hobby versus getting paid to do something with Mathics.

**Comment by mmatera** [comment]
> I'd like to see a section that helps us categorize priority. Something needed for a popular opens-source project (e.g. Rubi, KnotTheory) or a in order to support distribution,( e.g. SUSE, condaforge, PyPI) would be at one end. At the other end would be have been fooling around learning Mathematica and came across a couple of missing functions.
> 
> Another way to tackle this would be to ask for details as to why Mathics interests the person, e.g. personal hobby versus getting paid to do something with Mathics.

Not sure about how to do that. I do not want to have something too long that anyone wants to fill in. In any case, I want to see if this default form helps us to handle the current number of reported issues (and also for myself to be more tidy in writing them)

**Comment by rocky** [comment]
> > I'd like to see a section that helps us categorize priority. Something needed for a popular opens-source project (e.g. Rubi, KnotTheory) or a in order to support distribution,( e.g. SUSE, condaforge, PyPI) would be at one end. At the other end would be have been fooling around learning Mathematica and came across a couple of missing functions.
> > Another way to tackle this would be to ask for details as to why Mathics interests the person, e.g. personal hobby versus getting paid to do something with Mathics.
> 
> Not sure about how to do that. I do not want to have something too long that anyone wants to fill in. In any case, I want to see if this default form helps us to handle the current number of reported issues (and also for myself to be more tidy in writing them)

Ok - I will write something and merge it without discussion in the same manner as you just did. 

If I recall, I suggested Issue templates.

**Comment by mmatera** [comment]
> 
> Ok - I will write something and merge it without discussion in the same manner as you just did.
> 
sure, go ahead, or just remove the template files. However, it is not fair to say that there was not a previous discussion. You proposed it and I understood that all we agree that was a good idea. For some reason, we didn't it before, and I recalled it after writing the issue about formatting strings.

> If I recall, I suggested Issue templates.
Indeed.

**Comment by rocky** [comment]
> > Ok - I will write something and merge it without discussion in the same manner as you just did.
> 
> sure, go ahead, or just remove the template files. However, it is not fair to say that there was not a previous discussion. You proposed it and I understood that all we agree that was a good idea. For some reason, we didn't it before, and I recalled it after writing the issue about formatting strings.

You may have understood that ,but I am not seeing any indication of agreement or discussion [where I first proposed it](https://github.com/Mathics3/mathics-core/discussions/127)  late last January. Looking at that,  I see the same idea was raised there was omitted here. 

If there was some sort of "I don't know how to do" or "I don't agree" that would have been the proper place to bring that up and discuss this. 

And this also explains why I hadn't done this before - no feedback one way or another.

**Comment by mmatera** [comment]
I had the feeling that we discussed this with Thiago at some point. In any case, if you think that this requires more discussion, let's retire it. However, I think to have this default is better than do not have anything. So, is up to you

**Comment by TiagoCavalcante** [comment]
@mmatera @rocky I have a bad memory so I'll just skip the part of "we discussed that or not?", anyway it doesn't matter, what is ~~done~~ merged is ~~done~~ merged.

I like the current issue template, maybe it could also include "What you tried to do for fixing it?" or something like that.

> I do not want to have something too long that anyone wants to fill in.

I agree, currently, we don't have many issue fixers, we don't want to lose the issue reporters too.

**Comment by rocky** [comment]
> I had the feeling that we discussed this with Thiago at some point. 

He said he thought it was a good idea and was going to add this to another repository. 

> In any case, if you think that this requires more discussion, let's retire it. However, I think to have this default is better than do not have anything. So, is up to you

I agree it is better than nothing. So let's keep it.

I just wish that when you decide that you are interested in something that was brought up by someone else, you run your implementation or modification of that idea by the person who brought it up. Too often what I find is that it misses the mark in one way or another, or that the idea wasn't fully communicated or undersood.

**Comment by mmatera** [comment]
@rocky, OK, sorry for that. I am going to do a further step and implement what you wrote in #127, in a future PR. I didn't do that here because I had the hope to avoid distracting you by adding something in what we all agreed months ago that was a good thing, and that also has a decent default implementation. 
The point to do this now is that I am passing through several modules reviewing the documentation, and in some places I find aspects that I would like to record as issues. I thought  that having a structurated way to do it would be helpful.

**Comment by rocky** [comment]
> @rocky, OK, sorry for that. I am going to do a further step and implement what you wrote in #127, in a future PR. I didn't do that here because I had the hope to avoid distracting you by adding something in what we all agreed months ago that was a good thing, and that also has a decent default implementation. 

I thought it was a good idea when I proposed it. I don't see where you said something like yes, go again here in mathics-core. 

> The point to do this now is that I am passing through several modules reviewing the documentation, and in some places I find aspects that I would like to record as issues. I thought that having a structured way to do it would be helpful.

Ok. So write up the guide for yourself privately. *Then* create the issues that fall into that format. Then having concrete examples we can all look at and discuss. Then the last thing is to do the template after we've discussed this based on specifics.

**Pull request merged**
