### PR TITLE
fixing matrix inverse  (Issue #205)

### PR DESCRIPTION
**Pull request by mmatera**
Sympy  has troubles inverting matrices whose elements are functions. This PR fix the issue.

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/206"></a>

### CODE REVIEW

**Review by TiagoCavalcante — APPROVED** [review]
Edit: seems this isn't working, I wrote my comment before testing (only look at the code), and seems I can't delete my message.

**Comment by TiagoCavalcante** [comment]
@mmatera what I tested and didn't work also doesn't on Wolfram Cloud, so I guess this shouldn't be a dreaft.

**Comment by mmatera** [comment]
@TiagoCavalcante , what is exactly the issue? Could propose some test cases to check?

**Comment by TiagoCavalcante** [comment]
@mmatera this doesn't work for non-square matrices, although this is [defined](https://en.wikipedia.org/wiki/Generalized_inverse), Wolfram Language doesn't define inverse for non-square matrices, so that isn't a problem.

**Comment by mmatera** [comment]
Yes, WL has also builtins to deal with pseudoinverses and lateral inverses, but ``Inverse`` requires invertible square matrices.

**Comment by mmatera** [comment]
What is still missing here are a couple of pytest lines checking certain simple cases and error messages.

**Comment by TiagoCavalcante** [comment]
@mmatera ok, I'll add that tommorrow.

**Comment by TiagoCavalcante** [comment]
@mmatera I see your tests, I guess they are enough.

**Pull request merged**
