### PR TITLE
element.sort needs to handle incomparable elements

### LINKED ISSUE #446: Exception raised in `elements.sort()` when Image is multiplied by a number
## Description

In Mathics, an arithmetic expression like times on an  Image causes an exception.

## How to Reproduce

```
$ mathics -e 'Import["ExampleData/Einstein.jpg"] * 5 '  
```

## Output Given

```
Traceback (most recent call last):
  File "/tmp/.pyenv/versions/pyston-2.3.4/bin/mathics", line 33, in <module>
    sys.exit(load_entry_point('Mathics3', 'console_scripts', 'mathics')())
  File "/tmp/Mathics3/mathics-core/mathics/main.py", line 444, in main
    result = evaluation.evaluate(query, timeout=settings.TIMEOUT)
  File "/tmp/Mathics3/mathics-core/mathics/core/evaluation.py", line 362, in evaluate
    result = run_with_timeout_and_stack(evaluate, timeout, self)
  File "/tmp/Mathics3/mathics-core/mathics/core/evaluation.py", line 116, in run_with_timeout_and_stack
    return request()
  File "/tmp/Mathics3/mathics-core/mathics/core/evaluation.py", line 335, in evaluate
    self.last_eval = query.evaluate(self)
  File "/tmp/Mathics3/mathics-core/mathics/core/expression.py", line 474, in evaluate
    expr, reevaluate = expr.rewrite_apply_eval_step(evaluation)
  File "/tmp/Mathics3/mathics-core/mathics/core/expression.py", line 1122, in rewrite_apply_eval_step
    new.sort()
  File "/tmp/Mathics3/mathics-core/mathics/core/expression.py", line 1440, in sort
    elements.sort()
  File "/tmp/Mathics3/mathics-core/mathics/core/atoms.py", line 135, in __lt__
    else super().__lt__(other)
  File "/tmp/Mathics3/mathics-core/mathics/core/element.py", line 166, in __lt__
    return self.get_sort_key() < other.get_sort_key()
```

## Expected behavior

For multiplication, according to @mmatera the scalar is applied to each pixel element. (This behavior for black and white I find weird though and I don't know what the _precise_ definition of multiplying a bit value in the range [0,1] by 5 would mean. 

## Your Environment

all environments, current master: commit 1e23fd5744a22491a5815d7862f9c71b9f05d97c

## Additional context

See https://github.com/Mathics3/mathics-core/pull/447#issuecomment-1193324754

### PR DESCRIPTION
**Pull request by rocky**
Fixes #446 ?

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/447"></a>

### CODE REVIEW

**Comment by mmatera** [comment]
Shouldn't be better to provide as get_sort_key method to the element?

**Comment by rocky** [comment]
> Shouldn't be better to provide as get_sort_key method to the element?

Ok, but what does it mean to order two Images?

**Comment by mmatera** [comment]
In wma, you always can sort a couple of expressions. I have to check what is the behavior for this particular case.

**Comment by mmatera** [comment]
https://reference.wolfram.com/language/ref/Sort.html

**Comment by mmatera** [comment]
Here we are with an example:

imagen

* Arithmetic operations acts pixelwise.
* Smaller images comes before than larger ones. 
* Images are considered as expressions, which come after numbers and symbols.
* As expressions, are sorted by their head.

**Comment by rocky** [comment]
> Here we are with an example:
> 
> imagen
> 
> * Arithmetic operations act pixelwise on the image.
> * Smaller images come before larger ones.
> * Images are considered as expressions, which come after numbers and symbols.
> * As expressions, are sorted by their head.

I find this a little weird, but it is what it is. Given this complex thing, I don't want to touch any of this and will leave the issue open changing the description a little based on what I understand now.

**Comment by mmatera** [comment]
> > Here we are with an example:
> > imagen
> > 
> > * Arithmetic operations act pixelwise on the image.
> > * Smaller images come before larger ones.
> > * Images are considered as expressions, which come after numbers and symbols.
> > * As expressions, are sorted by their head.
> 
> I find this a little weird, but it is what it is. Given this complex thing, I don't want to touch any of this and will leave the issue open changing the description a little based on what I understand now.

The point is, that we do not need to reproduce exactly the same result of WMA for any pair of elements, but that every element in an expression should have a canonical sort key. #448 should provide a reasonable implementation and a fix for #446.

**Comment by rocky** [comment]
> > > Here we are with an example:
> > > imagen
> > > 
> > > * Arithmetic operations act pixelwise on the image.
> > > * Smaller images come before larger ones.
> > > * Images are considered as expressions, which come after numbers and symbols.
> > > * As expressions, are sorted by their head.
> > 
> > 
> > I find this a little weird, but it is what it is. Given this complex thing, I don't want to touch any of this and will leave the issue open changing the description a little based on what I understand now.
> 
> The point is, that we do not need to reproduce exactly the same result of WMA for any pair of elements, but that every element in an expression should have a canonical sort key. #448 should provide a reasonable implementation and a fix for #446.

This is a matter of opinion. But if you or others want to get closer to WMA and stop some place further, go for it!

**Pull request closed without merging**
