### PR TITLE
Fixing single \Mathics in docstrings

### PR DESCRIPTION
**Pull request by mmatera**
This PR fixes some possible misunderstood escaped characters, which now produce a warning.

### CODE REVIEW

**Comment by rocky** [comment]
LGTM. We are running into the same problems in testing seen in mathics-scanner

**Comment by mmatera** [comment]
@rocky, it looks like an incompatibility with the last version of sympy. Let's fix it in another PR.

**Comment by rocky** [comment]
> @rocky, it looks like an incompatibility with the last version of sympy. Let's fix it in another PR.

Yes, I see, a change somewhere between Sympy 1.12 and 1.13. 

Now a question is whether we want to do a release requiring 1.12 or delay release and fix for 1.13?

I suppose it depends on how much work is involved.

**Comment by mmatera** [comment]
I am going to investigate a little bit this weekend. Until now what I found was a change in the format of the numbers from mpmath that seems to confuse the Mathics formatter, and a movement in some functions of the sympy and scipy libraries. In the mean time we can force the older versions in master, and go forward with the release.

**Pull request merged**
