### PR TITLE
catch not known attributes in ClearAttributes and SetAttributes

### PR DESCRIPTION
**Pull request by mmatera**
@rocky, please before merging #607, add this patch, to a bug that came up trying to load FeynCalc

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/608"></a>

### CODE REVIEW

**Comment by rocky** [comment]
@mmatera ok - after this passes CI let's merge and I will rebase off of this.

**Comment by rocky** [comment]
@mmatera  If you have it, what is the exact error that occurs in FeynCalc?

**Comment by rocky** [comment]
This PR would suggest that Feyncalc has a bug which is hard to believe. So what changed in Mathematica?

**Comment by mmatera** [comment]
> @mmatera If you have it, what is the exact error that occurs in FeynCalc?

FeynCalc has a typo, that tries to Clear an attribute that do not exist. This patch just catch the exception.

Regarding the bug, it just tries to set ReadProtect attribute to some symbols, but there is a typo (something like ReadProtetc), that in WMA does not have any consequence, but here kills the kernel.

**Pull request merged**
