### PR TITLE
Replace Lena image with Hedy Lamarr image

### PR DESCRIPTION
**Pull request by TiagoCavalcante**

### CODE REVIEW

**Comment by TiagoCavalcante** [comment]
The error that is failing the tests is the following:
```
 E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/llvm-runtime_10.0-50~exp1_amd64.deb  503  Service Unavailable [IP: 20.106.104.242 80]
```

:upside_down_face:

**Comment by rocky** [comment]
> The error that is failing two tests is the following:
> 
> ```
>  E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/llvm-runtime_10.0-50~exp1_amd64.deb  503  Service Unavailable [IP: 20.106.104.242 80]
> ```
> 
> upside_down_face

Thanks. 

I am also seeing: 
> Exception cannot identify image file '/Users/runner/work/mathics-core/mathics core/mathics/data/ExampleData/hedy.tif'

This weekend I am focusing on trying to build a docker image with the existing changes.  It has been more of a struggle that I had imagined it would be.  After this is done I'll take a look if it is this is not resolved. For me it would probably be during  the week sometime.

**Comment by TiagoCavalcante** [comment]
@rocky I'll fix the errors in the tests later today

**Comment by TiagoCavalcante** [comment]
I'm having this error executing `mathics`:
```
AssertionError: ASCII operator to Unicode tables are missing from /usr/local/lib/python3.10/dist-packages/Mathics3-5.0.3.dev0-py3.10.egg/mathics/data/op-tables.json
```

BTW I'll only be able to update the tests tomorrow :disappointed:

**Comment by rocky** [comment]
> I'm having this error executing `mathics`:
> 
> ```
> AssertionError: ASCII operator to Unicode tables are missing from /usr/local/lib/python3.10/dist-packages/Mathics3-5.0.3.dev0-py3.10.egg/mathics/data/op-tables.json

Run `make` at the top level. That runs a program in `admin-tools` that creates the table.

> ```
> 
> BTW I'll only be able to update the tests tomorrow disappointed

NP.

**Comment by TiagoCavalcante** [comment]
@rocky could you give a look for in the test that is failing?

**Comment by rocky** [comment]
> @rocky could you give a look for in the test that is failing?

Sure.

**Pull request merged**
