### PR TITLE
Put test_rules_patterns tests where they belong

### PR DESCRIPTION
**Pull request by rocky**
Move tests into more specific tests for the module that the tests are in.

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/612"></a>

### CODE REVIEW

**Review by mmatera — APPROVED** [review]
LGTM

**Comment by mmatera** [comment]
Just one comment. The test are about how `Pattern` which is a class in mathics.core behaves over certain expressions, more than about how the mathics.builin.attributes module does. My guess is that the right place would be test.core.pattern.

**Comment by rocky** [comment]
> Just one comment. The test are about how `Pattern` which is a class in mathics.core behaves over certain expressions, more than about how the mathics.builin.attributes module does. My guess is that the right place would be test.core.pattern.

Ok - I will make the change. But I am not exactly sure which function(s) you are referring to. Please be more specific. Or if you want, feel free to commit on top of this.

**Comment by rocky** [comment]
I encourage moving tests around further later as we see fit. This is just a start.

**Pull request merged**
