### PR TITLE
More list expressions

### PR DESCRIPTION
**Pull request by rocky**
Go over parser/convert  and have it create ListExpression for list expressions
    
Try to make parser/convert less confusing by using more traditional Python practice, and add type annotations.

Do  our first has_form("List", None) removal. Many more will follow, but additional ListExpression cleanup is needed first.
    

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/508"></a>

### CODE REVIEW

**Comment by rocky** [comment]
This currently throws an exception in Boxing: 

```
Graphics[Circle[0], 1]
```

```
Exception raised: 'RowBox' object has no attribute 'boxes_to_svg' Traceback (most recent call last):
   File "mathics-django/mathics_django/web/views.py",
      line 588, in query result = evaluation.evaluate(expr, timeout=TIMEOUT)
   File "mathics-core/mathics/core/evaluation.py", line 365,
      in evaluate result = run_with_timeout_and_stack(evaluate, timeout, self)
    File "mathics-core/mathics/core/evaluation.py", line 119,
      in run_with_timeout_and_stack return request()
    File "mathics-core/mathics/core/evaluation.py", line 358,
      in evaluate return self.format_output(self.last_eval, format)
    File "mathics-django/mathics_django/web/models.py", line 32,
      in <lambda> evaluation.format_output = lambda expr, format: format_output(
    File "mathics-django/mathics_django/web/format.py", line 111,
      in format_output return eval_boxes(result, result.boxes_to_svg, obj) AttributeError: 'RowBox' object has no attribute 'boxes_to_svg'</lambda>
```

**Comment by rocky** [comment]
> This currently throws an exception in Boxing:
> 
> ```
> Graphics[Circle[0], 1]
> ```
> 
> ```
> Exception raised: 'RowBox' object has no attribute 'boxes_to_svg' Traceback (most recent call last):
>    File "mathics-django/mathics_django/web/views.py",
>       line 588, in query result = evaluation.evaluate(expr, timeout=TIMEOUT)
>    File "mathics-core/mathics/core/evaluation.py", line 365,
>       in evaluate result = run_with_timeout_and_stack(evaluate, timeout, self)
>     File "mathics-core/mathics/core/evaluation.py", line 119,
>       in run_with_timeout_and_stack return request()
>     File "mathics-core/mathics/core/evaluation.py", line 358,
>       in evaluate return self.format_output(self.last_eval, format)
>     File "mathics-django/mathics_django/web/models.py", line 32,
>       in <lambda> evaluation.format_output = lambda expr, format: format_output(
>     File "mathics-django/mathics_django/web/format.py", line 111,
>       in format_output return eval_boxes(result, result.boxes_to_svg, obj) AttributeError: 'RowBox' object has no attribute 'boxes_to_svg'</lambda>
> ```

The above is invalid input which causes the traceback. `Graphics[Circle[]]`, `Graphics[Circle[{1, 2}]]`  or `Graphics[Circle[{0, 0}, 1/2]]` work fine here.

**Review by TiagoCavalcante — APPROVED** [review]
LGTM

**Review by mmatera — APPROVED** [review]
LGTm

**Comment by rocky** [comment]
Note - This is a follow-on to functional-set_part

**Pull request merged**
