### PR TITLE
Start converting leaves -> elements

### PR DESCRIPTION
**Pull request by rocky**
I realize when other change X to Y it seems silly. But here X (leaves) is just plain wrong and Y (elements) is correct.

"elements" is the term Mathematica uses and it  is a perfectly appropriate term. 

"leaves" is just plain wrong. I don't know why but its bone headedness annoys me. It may have to do with this being at the level we find ourselves having to document, and then rework the code in the near future so we can get reasonable performance. Or maybe it is because I thought we were really talking about leaves of a tree and I now find this isn't correct and I am annoyed about having been confused by such a thoughtless kind of thing.

We have in the existing code running AtomQ on a "leaf" so see if it has children. This is confused/confusing.

It may seem a small thing, but if we can't think clearly about the code I think it is going to be harder to discuss it and improve it.

### CODE REVIEW

**Comment by rocky** [comment]
Although this commit is somewhat large, it is conservative, believe it or not. In other words I haven't been overly aggressive about finding _all_ of the opportunities. And in cases where something _might_ be leaves I've left it as is. For example if I create a list of Integers, integers being atoms would be leaves. 

There seems to be this `leaves` accessor function which may be inaccurate too. So those and things involving those I've left for some other time and PR. 

Finally it is kind of funny that we now sometimes see in graphical items `xxx.elements.elements`. The first element is an element of the graphic item, and the second element is some (possibly nested or structured) item in that. 

The way to address this is _not_ to call the second element a leaves (when it probably isn't), but rather to clarify that one thing is a xxx kind of element where the second thing is a yyy kind of element, e.g. possibly a generic graphics element.

**Comment by mmatera** [comment]
@rocky, if it is only a change of names, and you think is very helpful to change the misleading name, go ahead. The drawbacks I find here are:
* we need to change this in all the other projects.
* I would have to check but, in WL, I think the head of an expression is also an element.

**Comment by rocky** [comment]
> @rocky, if it is only a change of names, and you think is very helpful to change the misleading name, go ahead. The drawbacks I find here are:
> 
> * we need to change this in all the other projects.

I'll check the ones I know about. 

> * I would have to check but, in WL, I think the head of an expression is also an element.

Please check and let me know what you find.

**Comment by mmatera** [comment]
> > @rocky, if it is only a change of names, and you think is very helpful to change the misleading name, go ahead. The drawbacks I find here are:
> > 
> > * we need to change this in all the other projects.
> 
> I'll check the ones I know about.
> 

OK

> > * I would have to check but, in WL, I think the head of an expression is also an element.
> 
> Please check and let me know what you find.

No, you are right: https://reference.wolfram.com/language/guide/ElementsOfLists.html
The head is a *Part* of a list. The other parts are their  *elements*.

**Review by mmatera — APPROVED** [review]
LGTM

**Comment by rocky** [comment]
> @rocky, if it is only a change of names, and you think is very helpful to change the misleading name, go ahead. The drawbacks I find here are:
> 
> * we need to change this in all the other projects.
> * I would have to check but, in WL, I think the head of an expression is also an element.

I see one place in mathics django, and two places in mathicsscript.

So a very simple thing is to keep the get_leaves() function as an alias to get_elements() for a little bit.

But ideally if things were better designed in terms of how things get formatted we wouldn't have needed those to places to begin with .

**Comment by rocky** [comment]
> LGTM

Great! Let's do and iterate. @TiagoCavalcante if you have comments feel free to make them and we'll add them in the next round.

**Comment by TiagoCavalcante** [comment]
@rocky, ok. I agree that "leaves" was wrong.

**Pull request merged**
