### PR TITLE
Add builtin just once

### PR DESCRIPTION
**Pull request by mmatera**
This PR is one possible implementation for the @rocky 's idea that builtins (and autoload modules) should be loaded just once. 

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/620"></a>

### CODE REVIEW

**Comment by rocky** [comment]
As i mentioned in another PR, let me suggest some code and you can review. Thanks.

**Comment by mmatera** [comment]
Ok. This was just to illustrate the point.

**Comment by rocky** [comment]
> Ok. This was just to illustrate the point.

Ok. My takeaway with this is that there is some misunderstanding.

**Comment by TiagoCavalcante** [comment]
@mmatera just 2 Git tips:
- to not make the Git history complicated with merge commits you can use `git rebase branch_name` instead of `git merge branch_name`
- when things get complicated you can rewrite the history selecting only the commits you really want: `git log`, `git checkout master`, `git checkout -b branch_name_new`, and then for each commit you want to be in the branch `branch_name` do `git cherry-pick commit_SHA`, `git branch -D branch_name`, `git branch -m branch_name` and finally `git push -f`

**Comment by mmatera** [comment]
> @mmatera just 2 Git tips:
> 
>     * to not make the Git history complicated with merge commits you can use `git rebase branch_name` instead of `git merge branch_name`
> 
>     * when things get complicated you can rewrite the history selecting only the commits you really want: `git log`, `git checkout master`, `git checkout -b branch_name_new`, and then for each commit you want to be in the branch `branch_name` do `git cherry-pick commit_SHA`, `git branch -D branch_name`, `git branch -m branch_name` and finally `git push -f`

@TiagoCavalcante  thanks, and sorry for the noise. In any case, my mistake here was to put this in a PR instead of just cite the branch in the parent PR. The aim of this was just to understand @rocky 's idea.

**Pull request closed without merging**
