### PR TITLE
Allow a developer to overide to running Cython

### PR DESCRIPTION
**Pull request by rocky**
Set environment variable NO_CYTHON before running setup.py to avoid
running Cython even if it is installed.

### CODE REVIEW

**Comment by mmatera** [comment]
Excellent. Completely in favor! Can we also set the "No Cython" for git actions?

**Comment by rocky** [comment]
> Excellent. Completely in favor! Can we also set the "No Cython" for git actions?

Sure.

**Review by TiagoCavalcante — APPROVED** [review]
LGTM

**Comment by TiagoCavalcante** [comment]
@mmatera if Cython is not installed, it is not used, but I don't know if the Python workflow install that by default (but I guess that isn't installed).

**Pull request merged**
