### PR TITLE
fix PIL.Image

### PR DESCRIPTION
**Pull request by mmatera**
This PR just fix the import of PIL.Image in my setup (Pyston 2.3.4, PIL 8.4.0).

### CODE REVIEW

**Review by TiagoCavalcante — APPROVED** [review]
LGTM

**Comment by rocky** [comment]
Hmm... `mathics.drawing.image`  does not exist anymore. Instead, Image has been made its own guide section in #700 

So please try that out. And let's merge that instead.

**Comment by mmatera** [comment]
> Hmm... `mathics.drawing.image` does not exist anymore. Instead, Image has been made its own guide section in #700
> 
> So please try that out. And let's merge that instead.

If #700 is near to be finished, sure.

**Comment by mmatera** [comment]
Reimplemented in #704 over #700

**Comment by rocky** [comment]
> Reimplemented in #704 over #700

There is a lot more that _could_ be done. But this is now getting too large and probably should have been a couple PRs already. 

So my suggestion is merge and iterate.

**Pull request closed without merging**
