### PR TITLE
Only sets build_ext to Cython when NO_CYTHON isn't set

### PR DESCRIPTION
**Pull request by TiagoCavalcante**

### CODE REVIEW

**Comment by rocky** [comment]
This is just a formatting change, right? 

```
$ black setup.py 
All done! ✨ 🍰 ✨
1 file left unchanged.
```

**Comment by TiagoCavalcante** [comment]
@rocky no, I changed the indentation so it is inside the "if NO_CYTHON isn't set".

**Comment by rocky** [comment]
> @rocky no, I changed the indentation so it is inside the "if NO_CYTHON isn't set".

This then is a war of editors. My editor, GNU Emacs has an "comment region" and this is what it does. When that is uncommented it is indented exactly the way it should be for being inside the if.

**Review by rocky — APPROVED** [review]
LGTM - thanks for finding and fixing my buggy code.

**Pull request merged**
