### PR TITLE
Add cone

### PR DESCRIPTION
**Pull request by TiagoCavalcante**

### CODE REVIEW

**Comment by rocky** [comment]
Here is what I get when I try either of the examples: 

 System::exception:

```
Exception raised: 'Cone3DBox' object has no attribute 'points' Traceback (most recent call last):  File "/src/external-vcs/github/Mathics3/mathics-django/mathics_django/web/views.py", line 588, in query result = evaluation.evaluate(expr, timeout=TIMEOUT)  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/core/evaluation.py", line 361, in evaluate result = run_with_timeout_and_stack(evaluate, timeout, self)  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/core/evaluation.py", line 118, in run_with_timeout_and_stack return request()  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/core/evaluation.py", line 354, in evaluate return self.format_output(self.last_eval, format)  File "/src/external-vcs/github/Mathics3/mathics-django/mathics_django/web/models.py", line 33, in <lambda> evaluation, expr, format  File "/src/external-vcs/github/Mathics3/mathics-django/mathics_django/web/format.py", line 103, in format_output return eval_boxes(result, result.boxes_to_js, obj)  File "/src/external-vcs/github/Mathics3/mathics-django/mathics_django/web/format.py", line 32, in eval_boxes boxes = fn(evaluation=obj, **options)  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/builtin/box/graphics3d.py", line 333, in boxes_to_js json_repr = self.boxes_to_json(leaves, **options)  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/builtin/box/graphics3d.py", line 354, in boxes_to_json ) = self._prepare_elements(leaves, options)  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/builtin/box/graphics3d.py", line 312, in _prepare_elements final_pass=False  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/builtin/box/graphics3d.py", line 230, in calc_dimensions xmin, xmax, ymin, ymax, zmin, zmax = elements.extent()  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/builtin/drawing/graphics3d.py", line 192, in extent return total_extent_3d([element.extent() for element in self.elements])  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/builtin/drawing/graphics3d.py", line 192, in <listcomp> return total_extent_3d([element.extent() for element in self.elements])  File "/src/external-vcs/github/Mathics3/mathics-core/mathics/builtin/box/graphics3d.py", line 743, in extent for coords in self.points AttributeError: 'Cone3DBox' object has no attribute 'points'</listcomp></lambda>
``` 

(We really should fix up mathics-django to show tracebacks properly). 

And looking at the code I don't have see a "points" attribute in Cone3DBox.

**Comment by rocky** [comment]
Also - please install `pre-commit`: `pip install pre-commit` and then run `pre-commit install`

**Comment by TiagoCavalcante** [comment]
The error was happening because `graphics` is mandatory for `Coords3D`, I didn't know that because I forgot to run `make`. And I forgot of installing pre-commit in this container, already done.

**Comment by TiagoCavalcante** [comment]
image

**Review by rocky — APPROVED** [review]
LGTM - merge when you are ready.

One thing I notice in the shading is that you can see the flat ribs.  I wonder if there is a kind of mechanism that is analogous to spines for surfaces where basically a line (or in 3D a plain segment) is "smoothed"  by the adjacent surfaces listed.

**Comment by rocky** [comment]
@TiagoCavalcante When I compare  with Mathematica's `Graphics3D[Cone[]]` I see the same angled cone but it should be oriented tilted 45 degrees.

**Comment by TiagoCavalcante** [comment]
@rocky yes, the default value changes the angle. I kept the same default as `Cylinder`. We must also remember that the viewpoint changes the angle. The angle of the segment `(0, 0)--(1, 1)` is 45º, I didn't calculated, but my intuition says that that's also the angle of `(0, 0, 0)--(1, 1, 1)`.

**Comment by TiagoCavalcante** [comment]
@rocky yes, the default value changes the angle. I kept the same default as `Cylinder`. We must also remember that the viewpoint changes the angle. The angle of the segment `(0, 0)--(1, 1)` is 45º, I didn't calculated, but my intuition says that that's also the angle of `(0, 0, 0)--(1, 1, 1)`.

**Comment by TiagoCavalcante** [comment]
@rocky yes, the default value changes the angle. I kept the same default as `Cylinder`. We must also remember that the viewpoint changes the angle. The angle of the segment `(0, 0)--(1, 1)` is 45º, I didn't calculated, but my intuition says that that's also the angle of `(0, 0, 0)--(1, 1, 1)`.

**Comment by TiagoCavalcante** [comment]
> One thing I notice in the shading is that you can see the flat ribs. I wonder if there is a kind of mechanism that is analogous to spines for surfaces where basically a line (or in 3D a plain segment) is "smoothed" by the adjacent surfaces listed.

That already is being done but in a simple way.

The cone shader is derived from the Gouraud shader, there is the more advanced Phong shading. Increasing the number of segments would also help the shader (in a change of performance.

image

The decreasing of the flat ribs is almost none. The biggest change is when it is a shiny material (what it isn't).

Anyway, what neither Gouraud not Phong solves are the "steps" on the edges specially when the object is viewed from the top.

**Comment by TiagoCavalcante** [comment]
@rocky I believe the angle problem is mathics-threejs-backend side, not mathics-core side.

**Review by mmatera — APPROVED** [review]

**Comment by rocky** [comment]
Ok. Then let's merge and iterate later.

**Pull request merged**
