### PR TITLE
Guard against running Delete[] on an empty list.

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Comment by mmatera** [comment]
This is what happens in WMA:
```
In[1]:= Delete[{},0]                                                            

Out[1]= Sequence[]

In[2]:= Delete[{},1]                                                            

Delete::partw: Part {1} of {} does not exist.

Out[2]= Delete[{}, 1]

In[3]:= Delete[{},0]                                                            

Out[3]= Sequence[]

In[4]:= Delete[a,0]                                                             

Delete::partw: Part 0 of a does not exist.

Out[4]= Delete[a, 0]
```

**Comment by axkr** [comment]
> This is what happens in WMA:

Which version do you use?

In 14. 1:
```mma
In[1]:= Delete[{},0]                                                            
 
Out[1]= Identity[]
```

**Comment by mmatera** [comment]
> > This is what happens in WMA:
> 
> Which version do you use?
> 
I am using 12.2 and  13.2.0

In 14.1, what happens with
```
Delete[{1,2,3}, 0]
```
?

**Comment by axkr** [comment]
> In 14.1, what happens with
> 
> ```
> Delete[{1,2,3}, 0]
> ```
> 
> ?

```mma
Identity[1,2,3]
```

because
```mma
>> Sequence[1,2,3]

Identity[1, 2, 3] 
```

**Comment by mmatera** [comment]
> > In 14.1, what happens with
> > ```
> > Delete[{1,2,3}, 0]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?
> 
> ```mathematica
> Identity[1,2,3]
> ```
> 
> because
> 
> ```mathematica
> >> Sequence[1,2,3]
> 
> Identity[1, 2, 3] 
> ```

Until 13.2.0, `Identity` just accepted 1 argument. Also I wonder: Is this the "FullForm"? Or just the way in which WMA 14 formats `Sequence[...]` ?

**Comment by axkr** [comment]
> Until 13.2.0, `Identity` just accepted 1 argument. Also I wonder: Is this the "FullForm"? Or just the way in which WMA 14 formats `Sequence[...]` ?

Not sure. I think it's evaluated in the backend. A `General::argx` message `Identity called with 0 arguments; 1 argument is expected` is also printed.

**Review by mmatera — APPROVED** [review]
LGTM

**Pull request merged**
