### PR TITLE
Allow using Sympy 1.9

### PR DESCRIPTION
**Pull request by rocky**
Sympy 1.9 is out and it seems to work without problems. Allow (but don't require) it.

### CODE REVIEW

**Comment by TiagoCavalcante** [comment]
Seems jut 1 test fails, I'll try to fix that tommorrow.

**Comment by rocky** [comment]
> Seems just 1 test fails, I'll try to fix that tommorrow.

@TiagoCavalcante  Thanks!

**Comment by TiagoCavalcante** [comment]
@rocky what is happening here is that Sympy isn't returning `Indeterminate` for the expression `Integrate[-Infinity, {x, 0, Infinity}]`, but that is keeping the expression as is. Then the apply function converts that expression to a Mathics Expression, which again is `Integrate[-Infinity, {x, 0, Infinity}]`, then the apply method is called again...
A way to fix this is the atom `Integrate` instead of the expression integrate.

**Comment by rocky** [comment]
@TiagoCavalcante  Thanks for doing this. Looks good to me!

**Pull request merged**
