### PR TITLE
Walk parts bench

### PR DESCRIPTION
**Pull request by mmatera**
@rocky, @TiagoCavalcante  here we go with a first (and very raw) unit test for walk_parts. When the framework gets clearer, maybe we can move this code to mathics-bench

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/52"></a>

### CODE REVIEW

**Comment by TiagoCavalcante** [comment]
@mmatera should I move the tests to mathics-benchmark?

**Comment by mmatera** [comment]
If you figure out where to put it, go ahead..

**Comment by TiagoCavalcante** [comment]
@mmatera now mathics-benchmark supports Python code.

**Comment by mmatera** [comment]
> @mmatera now mathics-benchmark supports Python code.

In that case, when I get some time I will see how to put this in mathics-benchmark. Let's keep this PR open until that, to avoid lose it.

**Comment by mmatera** [comment]
@TiagoCavalcante, I rebase this to recover the relevant file. Maybe we can try just to copy to mathics-benchmark  to see how to integrate it.

**Comment by TiagoCavalcante** [comment]
@mmatera the SymbolAll part can be merged, in mathics-benchmark using python is almost the same as using Mathics code, you just need to add this line in the benchmark file:
https://github.com/Mathics3/mathics-benchmark/blob/71bf69ff981978cb5bdb59bb9a486dd7d6cc9b94/benchmarks/example.yaml#L33

So yes, it is a kinda copy-paste.

**Comment by mmatera** [comment]
Moved into mathics-benchmarks

**Pull request closed without merging**
