### PR TITLE
Faster attributes

### PR DESCRIPTION
**Pull request by mmatera**
This PR contains the first part of the changes in the logic included in PR #61

### CODE REVIEW

**Review by TiagoCavalcante — APPROVED** [review]
LGTM

**Comment by axkr** [comment]
Shouldn`t attributes be simply mapped from a "integer bit set" which is associated to each symbol?
- https://github.com/axkr/symja_android_library/blob/23785923ee5f5ef075692e1778c97759543ddf7b/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/interfaces/ISymbol.java#L29

**Comment by mmatera** [comment]
Yes, probably that would be faster. Something that we could do to keep the flexibility of the current implementation is to keep a bitmask in the definitions object that mirrors the stored attributes.

**Comment by TiagoCavalcante** [comment]
@mmatera @rocky I think we could create a module with the attributes constants, then import them. Somethin like it:
current:
```
class F(Builtin):
    attributes = ("Protected", "ReadProtected")
```
new:
```
from mathics.attributes import Protected, ReadProtected

class F(Builtin):
    attributes = Protected | ReadProtected
```

If you agree, I can do this next week.

**Comment by mmatera** [comment]
Looking at   https://reference.wolfram.com/language/ref/Attributes.html

I think, yes, it makes sense.

**Comment by rocky** [comment]
Go for it!

**Comment by TiagoCavalcante** [comment]
@mmatera I think all these changes except the last can the combined with attributes-bitset (I'm not sure about the last).

**Comment by mmatera** [comment]
@TiagoCavalcante I think so. Let's try to merge it into another branch to see how they get on together.

**Comment by mmatera** [comment]
This PR is deprecated.

**Pull request closed without merging**
