### PR TITLE
Benchmarking+futher improvements fully working

### PR DESCRIPTION
**Pull request by mmatera**
@rocky,  here I added the changes from #401 that make that this branch passes all the tests.

<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/402"></a>

### CODE REVIEW

**Comment by rocky** [comment]
The way I have been handling this is just to rebase off of master. So after #401 goes in, let's do that..

**Comment by rocky** [comment]
When I rebased and ran `pytest -s test/package/test_combinatorica_benched.py` I see a categorical gain in speed. 

https://github.com/Mathics3/mathics-core/commit/ed8c5d5207d61abed8fd0dffa60e0089d3d4cd12 has the details.

I expected a slowdown would happen when fixing bugs though.

**Comment by mmatera** [comment]
> When I rebased and ran `pytest -s test/package/test_combinatorica_benched.py` I see a categorical gain in speed.
> 
> [ed8c5d5](https://github.com/Mathics3/mathics-core/commit/ed8c5d5207d61abed8fd0dffa60e0089d3d4cd12) has the details.
> 
> I expected a slowdown would happen when fixing bugs though.

Actually, we still could get something better if we could use the `expressions_properties` parameter in the constructor. However, it seems that in some places we fail to predict what the internal `_build_elements_properties` would produce.

**Comment by rocky** [comment]
> Actually, we still could get something better if we could use the `expressions_properties` parameter in the constructor. However, it seems that in some places we fail to predict what the internal `_build_elements_properties` would produce.

https://github.com/Mathics3/mathics-core/discussions/400#discussioncomment-3013481 has one place that needs fixing.

**Comment by mmatera** [comment]
Yes, I have an eye on it. But it seems that three are several places with similar problems.

**Pull request closed without merging**
