### PR TITLE
Romberg is deprecated...

### PR DESCRIPTION
**Pull request by rocky**
and will be removed by SciPyi 1.15

### CODE REVIEW

**Comment by rocky** [comment]
Scipy has `dblquad`, `tplquad, and  `cumulative_trapezoid`  that we don't currently support. But that is left to someone who understands this better.  It also looks like we don't use SciPy's `simpson`.

**Comment by mmatera** [comment]
> Scipy has `dblquad`, `tplquad`, and `cumulative_trapezoid` that we don't currently support. But that is left to someone who understands this better. It also looks like we don't use SciPy's `simpson`.

I didn't include these methods because they do not accept general functions as an argument. `dblquad`, `tplquad` only work for 2 and three variable functions respectively, while `cumulative_trapezoid` and `simpson` estimate integrals using arrays of numbers instead of functions.

**Review by mmatera — APPROVED** [review]
LGTM

**Comment by rocky** [comment]
> > Scipy has `dblquad`, `tplquad`, and `cumulative_trapezoid` that we don't currently support. But that is left to someone who understands this better. It also looks like we don't use SciPy's `simpson`.
> 
> I didn't include these methods because they do not accept general functions as an argument. `dblquad`, `tplquad` only work for 2 and three variable functions respectively, while `cumulative_trapezoid` and `simpson` estimate integrals using arrays of numbers instead of functions.

Thanks for the explanation.

Down the line, it might be possible to analyze the expression passed to determine when these are applicable and handle these. However, with all the other stuff to do, that's best left for when a situation that needs these arises.

**Pull request merged**
